### ISSUE TITLE
tweet with image (and location) sent without message

### ISSUE THREAD

**Issue by kimmoli** [veskuh/Tweetian#107]
i just tweeted with image and location, and i can see only the image on the tweet?

**Comment by veskuh** [comment]
Do you have this commit?
https://github.com/veskuh/Tweetian/commit/9c34df2cbba187a5e63ab53a2766ee6e84bc1622

**Comment by kimmoli** [comment]
i'm not that fast. i'll try when i get my pc to network...

**Comment by kimmoli** [comment]
Tested 7d2e5bee with image attachment and now it works.
