### ISSUE TITLE
Proposed tweetview rework

### ISSUE THREAD

**Issue by Morpog** [veskuh/Tweetian#111]
Hi veskuh,

I tried to optimized the tweetview a bit to show more content on one page. I started with timeline, mentions and tweetpage, so if you like it, I can continue with the other views like DirectMsg and Search, etc. If not, I can save the time doing it :D

Timeline
http://abload.de/img/sailfishosemulator7fjd7.png

Tweetpage
http://abload.de/img/sailfishosemulator2nojx0.png

Tweetpage retweeted
http://abload.de/img/sailfishosemulator3e7jta.png

Tweetpage favorited
http://abload.de/img/sailfishosemulator4gqkld.png

Tweetpage conversation
http://abload.de/img/sailfishosemulator5zsjyt.png

Greets
Morpog

**Comment by veskuh** [comment]
Looks good. 

I'm not sure about aligning the metadata in  timeline to left, but if you think its better then I'm fine with it.
