### ISSUE TITLE
Active Cover

### ISSUE THREAD

**Issue by veskuh** [veskuh/Tweetian#12]
ActiveCover is typical concept in Sailfish applications. 

The cover could show for example 1-3 tweets or alternatively amount of unseen tweets, unseen mentions, and unseen directmessages. The actions could be reload and new tweet.

**Comment by siteshwar** [comment]
How would the "new tweet" action work ? Open the new tweet page in full screen ?

**Comment by veskuh** [comment]
Yes, bring app to foreground and push neetweetpage on top of pagestack.

**Comment by siteshwar** [comment]
@veskuh This can be closed now.
