### ISSUE TITLE
Clicking image on user page does not work properly

### ISSUE THREAD

**Issue by siteshwar** [veskuh/Tweetian#130]
User's profile image will open in full view only if you click at the bottom half of the preview image, clicking on top half part of user's profile image does not do anything.

**Comment by siteshwar** [comment]
I see similar behaviour in my timeline, not able to open tweet page by clicking on top part of first tweet.

**Comment by veskuh** [comment]
There is two possible reasons. 
1) pulley menu steals clicks on that area
2) compositor reserves some are to detect system wide edge gestures.
Either case, its hard to do anything else than make sure that tweet & icon are big enough and have enough padding around them. On device I have not experienced this to be problem so far.

**Comment by Morpog** [comment]
Works flawless here in emulator and device.

**Comment by siteshwar** [comment]
@Morpog Are you using latest SDK ?

**Comment by Morpog** [comment]
Yes, latest.
http://abload.de/img/unbenanntvfb8q.png

**Comment by veskuh** [comment]
2.0.4 has fix for touch handling in top part of the screen. To me it looks like same issue as this one.
