### ISSUE TITLE
https://flic.kr/ Links don't work

### ISSUE THREAD

**Issue by huellif** [veskuh/Tweetian#147]
For me links in this format:
https://flic.kr/p/n8eE9T

don't show up as Flickr images and there's no preview.

I am not familiar with the Flickr API and can't manage to successfully add this URL format and encoding to Flickr.js, maybe somebody can fix it.

**Comment by veskuh** [comment]
AFAIK, this should be fixed in 2.0.4

**Comment by huellif** [comment]
Hello veskuh,

Latest Flickr.js is included (with https://github.com/veskuh/Tweetian/commit/4673840bc02f3dbde712dc25f37934bae405c877#diff-1161f65bf36bf620831e5582ff6e3283 )

and now it works fine :)

Thanks in advance!

Regards
