### ISSUE TITLE
Landscape for images

### ISSUE THREAD

**Issue by veskuh** [veskuh/Tweetian#15]
Imageviewer should support landscape

**Comment by siteshwar** [comment]
@veskuh I won't be able to work on it as I don't have a real device and emulator does not support landscape mode. So please take up this issue.

**Comment by veskuh** [comment]
Sure. Working on it.

**Comment by veskuh** [comment]
Fixed in https://github.com/veskuh/Tweetian/commit/5dc22ed47af9fe05a44a1f0358120085cd286c93
