### ISSUE TITLE
Profiles broken

### ISSUE THREAD

**Issue by Vistaus** [veskuh/Tweetian#153]
After the last commit (but presumably because of Twitter rolling out the new profiles to everyone) profiles are broken. When you click someone's profile or long press --> @ username's profile, nothing happens.

**Comment by veskuh** [comment]
Hmm.. Strange. Profile works ok when I try to replicate this.

**Comment by Vistaus** [comment]
I found out that profiles still work with the previous commit (about a month ago?). With the latest commit, it's broken. Own profile works, but profiles from others don't with the latest commit.

**Comment by veskuh** [comment]
I'm not seeing anything related to profiles in latest commits and like I said works fine on emulator and device for me. If you built tweetian yourself this may be unclean build or something that I've forgotten to submit to github. 

You can try to see if my latest .rpm (uploaded today) suffers from the same issue: https://openrepos.net/sites/default/files/packages/1159/harbour-tweetian-2.0.3-1.armv7hl.rpm

Another thing to notice is that API key in my rpm is obviously different than what is in sources so you may need to log out and log in again.

**Comment by Vistaus** [comment]
With the very latest commit this is fixed now. Thanks :)
