### ISSUE TITLE
Errors in startup

### ISSUE THREAD

**Issue by veskuh** [veskuh/Tweetian#16]
[W] unknown:-1 - <Unknown File>: Can't assign to existing role 'id' of different type [String -> Number]
[W] unknown:-1 - <Unknown File>: Can't assign to existing role 'createdAt' of different type [String -> DateTime]

**Comment by veskuh** [comment]
Fixed in https://github.com/veskuh/Tweetian/commit/fcb396a70cae0dc2606f369ab2c277e66fa5c635

**Comment by siteshwar** [comment]
I am getting following error at startup :

```
Unable to open input file: No such file or directory
```
