### ISSUE TITLE
Cannot sign in (no browser page opens)

### ISSUE THREAD

**Issue by janaurka** [veskuh/Tweetian#160]
I had to reconnect my twitter account with tweetian, which does not work with `1.0.8.19`. Tried to reinstall the upstream and other (1.8.x) versions. Thet all did not work.

Tried also to delete files of tweetian after removing the app (`rm -f ~/.cache/harbour/harbour-tweetian/`) but there is still no browser window to sign in to twitter.

**Comment by veskuh** [comment]
Also, do rm -f rm .local/share/harbour-tweetian/ to remove rest of data.

This shouldn't affect browser opening however. I have no issues with opening browser from latest version, open repos version or harbour version.

Are you sure your browser is working normally? It opens links from other apps just as it did before?

**Comment by janaurka** [comment]
Sorry, the problem somehow vanished and i’ve forgotten to close this bug.

Cannot really say, what worked, but some days later, when i’ve tried again, the browser opened itselft and i was able to login normally.
