### ISSUE TITLE
Version 2.0.4-1 requires qt5-qtdeclarative-import-location

### ISSUE THREAD

**Issue by arnbak** [veskuh/Tweetian#164]
Updated to the newest version from openrepos required me to install qt5-qtdeclarative-import-location package to be able to tweet.

```
[W] unknown:111 - file:///usr/lib/qt5/qml/Sailfish/Silica/PageStack.js:111: Error: Error while loading page: qrc:/qml/tweetian-harmattan/NewTweetPage.qml:21 module "QtLocation" is not installed
```

Just wondering why this is suddenly a requirement ?

**Comment by veskuh** [comment]
In the OpenRepos version it has been a requirement from the beginning. Location is used when user wants to attach location info (from the pulley menu) to the tweet. Jolla Store version does not yet allow location API so the Jolla store version has not had this functionality.

**Comment by arnbak** [comment]
Thanks
