### ISSUE TITLE
VKB should open automatically on tweet editor

### ISSUE THREAD

**Issue by veskuh** [veskuh/Tweetian#17]
VKB should open automatically on tweet editor page for new tweets and replies

**Comment by siteshwar** [comment]
On the emulator virtual keyboard opens automatically. Isn't it ? Are there any issues on the devices only ?

**Comment by veskuh** [comment]
VKB opens when I tap on the input field. I'd like to see it opening automatically (with focus on the input field) when user enters the page so that he does not need to tap on the input field and can just start typing the tweet.

**Comment by veskuh** [comment]
Merged. Thanks.
