### ISSUE TITLE
List timeline is not working

### ISSUE THREAD

**Issue by veskuh** [veskuh/Tweetian#171]
in 2.0.5 list timeline does not load and remains busy forever.

**Comment by veskuh** [comment]
Fix: https://github.com/veskuh/Tweetian/commit/8cff34a40ebaee93a3a95bead90a0cce37213a34

Will mark the issue closed once released.

**Comment by DeepPurple15x** [comment]
Please release this soon. I only use Twitter List especially for News.

**Comment by veskuh** [comment]
2.0.6 is at openrepos and has the fix.
