### ISSUE TITLE
Show feedback when URL is clicked in a Tweet

### ISSUE THREAD

**Issue by anandrkris** [veskuh/Tweetian#174]
I suppose it is a Tweetian issue and not Sailfish issue - (Apologies, if am wrong)
When i press on URL's to open them there is no feedback to tell that i have clicked on it. Have seen circular progress bar / busy like icon elsewhere to indicate that something is happening (browser being opened). 
Also, at times I feel opening URL's does not happen on first press or that i have to be very precise on clicking, maybe i am doing something wrong! Could you please check if this can be improved. Thanks.

**Comment by veskuh** [comment]
Tweetian shows notification banner when user clicks on link. With Sailfish 1.1.0.38 the transition away from Tweetian (at least for me) is so quick that you see the banner only briefly.

**Comment by anandrkris** [comment]
Oh! Maybe its too quick and thats why I never came across the notification banner. 
Not sure if there is any Sailfish standard for clicks - Can this be implemented in any other fashion? - like URL color change on clicking or some progress indicator...
Anyways, thanks for replying...

**Comment by veskuh** [comment]
Buttons and icon buttons change their color while pressed, similarly here press could be indicated by changing link's color.

**Comment by benaryorg** [comment]
Can this issue be closed by now?

**Comment by anandrkris** [comment]
Just noting that am able to see the banner these days upon clicking...So, am happy with closing this :smile:
