### ISSUE TITLE
Timestamp shows time of retweet instead of time of the original tweet

### ISSUE THREAD

**Issue by schmittlauch** [veskuh/Tweetian#188]
The timestamp displayed at retweets is the time of the originaltweet being retweeted, not the time of the original tweet being posted. This can lead to irritation, as I have sometimes replied to tweets which were some months old but had been retweeted a few minutes ago.

**Comment by veskuh** [comment]
Makes sense to change this. Official client uses original timestamp too.

**Comment by veskuh** [comment]
released in 2.0.7

**Comment by Manik-Taneja** [comment]
Hey, I was trying to get the timestamp of the retweet is it possible?
