### ISSUE TITLE
OnePlus X - the size of the icons

### ISSUE THREAD

**Issue by lewadedun** [veskuh/Tweetian#206]
![screenshot-16-07-03-19-34-10](https://cloud.githubusercontent.com/assets/9382415/16546009/a3c65eae-4155-11e6-888a-8698cef34268.png)
Can you fix it?

**Comment by M4rtinK** [comment]
Looks like HiDPI rendering issue, like fixed size icons being too small on a screen with high DPI.

**Comment by lewadedun** [comment]
Yes, and this problem is on all phones with a different resolution, I think

**Comment by veskuh** [comment]
On 2.0.8 and newer has this fixed.

**Comment by ghost** [comment]
@veskuh, can you upload an i486 RPM of the latest version to OpenRepos as well?
