### ISSUE TITLE
Account details page broken with SFOS 2.1.0.9

### ISSUE THREAD

**Issue by schmittlauch** [veskuh/Tweetian#210]
Since updating SailfishOS to 2.1.0.9, the account details page is broken: Only the header image, profile pic remain where they should be, most of the other elements are now positioned wrongly and overlapping at the top left corner (see screenshot).

It's probably related to Qt 5.6

![screenshot_20170210_001](https://cloud.githubusercontent.com/assets/1479555/22808304/8591db78-ef2b-11e6-81a9-d874217d5324.png)

**Comment by veskuh** [comment]
Fixed in 2.0.9. Available in openrepos now will be in Jolla Store later.

**Comment by schmittlauch** [comment]
thx. What is the current development branch? I don't see any commits since the end of 2016.

**Comment by veskuh** [comment]
You are looking at right place (sailfish-port). No commits after end of 2016.

**Comment by schmittlauch** [comment]
so just a rebuild?
