### ISSUE TITLE
Flick between tabs sometimes breaks

### ISSUE THREAD

**Issue by veskuh** [veskuh/Tweetian#3]
Flick between tabs sometimes breaks and you cannot scroll up or down anymore

**Comment by veskuh** [comment]
This seems to be an issue with SilicaListView. I finally figured out a workaround. By using SlideshowView as parent for the tabs instead of horizontal SilicaListView the view no longer gets confused about flick orientation. Should be fixed in next release.

**Comment by Morpog** [comment]
It not only gets confused and breaks scrolling, it also jumps around between tabs. I can provide a video if you cannot reproduce. It's the only real annoying bug left. If I understand that correctly it will be fixed with next SailfiishOS release?

**Comment by veskuh** [comment]
Silica fix will take longer. I did a workaround. This should fix both issues: https://github.com/veskuh/Tweetian/commit/a1149aac5c7acd48c74db00ca912d7369e430df3

Pushing update to openrepos tonight.

**Comment by veskuh** [comment]
Fixed in 1.8.3-2
