### ISSUE TITLE
Timestamp do not follow

### ISSUE THREAD

**Issue by veskuh** [veskuh/Tweetian#41]
Timestamp do not follow locale. for example in finnish we have AM/PM even though the device has 24h clock as locale setting

**Comment by siteshwar** [comment]
While working on this task I found that after starting Tweetian if you change your timezone, then it will store wrong timestamps for all the older tweets. I haven't been able to find what's causing this however.

**Comment by veskuh** [comment]
Ok, I'll file that issue.
