### ISSUE TITLE
Errors in Trends & Search page

### ISSUE THREAD

**Issue by veskuh** [veskuh/Tweetian#50]
Error in logs:
 <Unknown File>: Can't assign to existing role 'id' of different type [String -> Number]

**Comment by siteshwar** [comment]
I am not getting any such errors on Trends and Search page.

**Comment by siteshwar** [comment]
I was able to reproduce this error after fixing #52. Tweetian gives these errors only if it has some saved searches. I have updated my pull request #61 to fix this issue (through e61ee39).

**Comment by veskuh** [comment]
Works now.
