### ISSUE TITLE
Feature to fast scroll to top

### ISSUE THREAD

**Issue by ghost** [veskuh/Tweetian#51]
I think it would be a good idea to add FancyScroller.qml used in apps like unnoficialtogether, Tidings and Webcat.

What fancy scroller do is add small icons when scrolling up/down to make it easy to fast scroll to top/bottom.

see: https://github.com/mike7b4/unofficialtogether/blob/master/qml/pages/FancyScroller.qml

**Comment by siteshwar** [comment]
@mike7b4 You can quickly scroll to top by clicking on the tab headers.

I would check FancyScroller. Thanks for mentioning it.

**Comment by ghost** [comment]
hmm what tab headers? confused...

**Comment by veskuh** [comment]
Since toolbar in the bottom is for selecting tabs in code those are "tab headers" also because in original tweetian the bar was on top.

**Comment by Morpog** [comment]
I like the fancyscroller idea. But visually I would prefer it without that colored background. Like it's done in communi-sailfish.

See:
https://github.com/communi/communi-sailfish/commit/c94b94809794daf02cac5dd70b8270d05e695cad
https://github.com/communi/communi-sailfish/commit/6e62d919971b1dc32e48e4a110d1dfb4640deb07

The arrow icons are from me, I can commit them here too if wanted. The original theme icons look fringed, thats why I fixed them there. Must be the reason why mike7b4 used that colored background.

But as veskuh says, the tab bar buttons already do the trick.

**Comment by ghost** [comment]
Agree transparent arrows like communi and tidings looks better. 

We probadly will change that in jolla2gether also.

**Comment by veskuh** [comment]
PR is https://github.com/veskuh/Tweetian/pull/134

**Comment by veskuh** [comment]
released in 2.0.3.
