### ISSUE TITLE
Streamline More page

### ISSUE THREAD

**Issue by Morpog** [veskuh/Tweetian#56]
When opening more, it should show contents of general and update settings on that page. Move about, muting, user information and sign out to a pulley on that page.

**Comment by veskuh** [comment]
This is a good suggestion, that makes the page look and behave better. 

One related idea was also to put "About me" in own tab in main level since people look their own profile quite often (followers, lists and such).

**Comment by siteshwar** [comment]
This has been addressed through c44c9cf4a7b0fcf6093b6cefa474a6a0849b94bf
