### ISSUE TITLE
Tweetlist remains empty after start

### ISSUE THREAD

**Issue by veskuh** [veskuh/Tweetian#62]
This is just happening with Sailfish OS 1.0.3.8, Naamankajärvi. Flicking sideways fills the view correctly and all is fine after that.

**Comment by nulani** [comment]
Ditto, also after upgrade to 1.0.3.8. At least Tweetian didn't lose its settings like a lot of other apps.

**Comment by veskuh** [comment]
Fixed in 1.8.3-3
