### ISSUE TITLE
subview under userinfo do not use PageHeader as in platform style

### ISSUE THREAD

**Issue by veskuh** [veskuh/Tweetian#7]
Typically in Silica pageheaders are scroll along with list. In subviews under "User info" they are static. We should follow platform style.

**Comment by veskuh** [comment]
So User Info page behaves correctly. The header title "@ user" moves when I flick the page. In the subviews of that view PageHeader (=title text) is wrongly in fixed position on top of the screen.

**Comment by siteshwar** [comment]
This has been fixed.
