### ISSUE TITLE
Attach images to tweet

### ISSUE THREAD

**Issue by veskuh** [veskuh/Tweetian#9]
Tweetian on other platforms supports attaching images to tweets, this is still disabled in Sailfish-port

**Comment by siteshwar** [comment]
How should I implement file chooser ?

**Comment by veskuh** [comment]
Well, the annoying part is that we really shouldn't need to do anything. There is already image picker in platform, but unfortunately it is not allowed to be used by harbor apps just yet. The second best thing would be to get images from QtDocGallery and just put them to dialog with a silicagridview just like in SDK example. Bad news here again. QtDocGallery is not yet an accepted API either.

So to implement this what is needed is either to wait for APIs to open up or to create a C++ model which retrieves paths of images from filesystem. The images are stored in QStandardPaths::PicturesLocation (there may be subdirectories under it). And the picker would be SilicaDialog with SilicaGridview on it.

**Comment by siteshwar** [comment]
I believe you should reconsider your choice of making new tweet page a dialog. I am having problems while attaching images with tweets since the dialog which contains all the information about image is deleted after accepting while the image upload is going on (See the imageUploader component on new tweet page).

**Comment by veskuh** [comment]
I'm fine with going back to old approach. UI with dialog is more gesture based, but IMO not necessarily better.

**Comment by siteshwar** [comment]
Can you point me to an example which uses platform image picker ? Are you referring to this http://qt-project.org/doc/qt-5.1/qtquickdialogs/qml-qtquick-dialogs1-filedialog.html ?

EDIT: I found it in Sailfish.Pickers QML module.
