### ISSUE TITLE
TrendsPage in slideshowview is not always shown on top

### ISSUE THREAD

**Issue by Morpog** [veskuh/Tweetian#96]
Seems like the view is sometimes top anchored to PageHeader and sometimes to SectionHeader. Dunno why and when it happens.

**Comment by Morpog** [comment]
This should be fixed before submitting a new build to harbour.

**Comment by veskuh** [comment]
Fixed in https://github.com/veskuh/Tweetian/commit/0321868fa3a76026f651184515b87cd4749c2098
