### ISSUE TITLE
Unfollowing someone should use a remorse action

### ISSUE THREAD

**Issue by hoelzro** [veskuh/Tweetian#99]
Unfollowing someone currenty prompts them to accept or decline; I think it should use a remorse action instead for more of the "native" Sailfish feel.  (This of course only applies to the Sailfish port)

**Comment by veskuh** [comment]
Yes, sure. There is probable other places too where remorse item should be used.

**Comment by siteshwar** [comment]
Can we have a RemorsePopup defined in main.qml which can be used across the application ?

**Comment by veskuh** [comment]
Technically it may be possible, but IMO it would make code more complex.

UI wise it is not OK. If you for example do unfollow action under user's page, the popup should open on top of the user page and if you navigate away, then the action should be executed immediately and popup should go away. And this pretty much happens automatically if you define the remorse popup in that page. The point of the popup is just to create easy way to cancel immediately after you realize you are making a mistake, so it should not distract you for too long.

**Comment by veskuh** [comment]
Fixed in PR #131
